In [36]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

iris = datasets.load_iris()


# First two columns from iris.data
# CONVENTION x = features, y = target
X = iris.data[:, :2] 
# NOTE: (Last two colums is more accurate than the first two - see graphs)
# Howeverm in this example the first two columns are used.
y = iris.target

print iris.data
print X
print y

# Supervised learning - Supply the data and the results
# Classification problem - There is a target - discrete predictions 
# rather than regression with predicts a  more exact value


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [37]:
# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

# The test size is 0.25 or 25% of the whole dataset. 
# A random state of one fixes the random seed of the function 
# so that you get the same results every time you call the 
# function, which is important for now to reproduce the same 
# results consistently.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)


In [38]:
# Now load an estimator
from sklearn.svm import SVC

# Create an instance of a linear SVC (support vector classifier)
clf = SVC(kernel='linear',random_state=1)

# return a trained model
clf.fit(X_train, y_train)
# clf variable is now fitted/trained

# Generate predictions based on X
y_pred = clf.predict(X_test)
# Predicted y results
print(y_pred)
# Actual y results
print(y_test)

# Get accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))


[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]
0.9736842105263158


In [35]:
# SUMMARY 
#
# To summarize, we will do all the steps with a different algorithm, 
# logistic regression.

# Steps:
# 1. Import LogisticRegression
from sklearn.linear_model import LogisticRegression

# 2. Split the data into training and testing sets
#    - All rows and FIRST two columns
X = iris.data[:, :2]
#    - Set y as the target
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

# 3. Create and train the model using the fit function
clf = LogisticRegression(random_state = 1)
clf.fit(X_train, y_train)

# 4. Predict the test observations
y_pred = clf.predict(X_test)

# 5. Measure the accuracy
accuracy_score(y_test,y_pred)

/home/josh/.local/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/josh/.local/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.6052631578947368